name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  date-difference:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate date difference
        run: |
          FIXED_DATE="1998-03-21"
          CURRENT_DATE=$(date +%F)
          DIFF=$(($(date -d $CURRENT_DATE +%s) - $(date -d $FIXED_DATE +%s)))
          DIFF_DAYS=$(($DIFF / 86400))
          echo "Difference in days: $DIFF_DAYS"

  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: Santti4go/metrics@test-terminal
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
